### ISSUE TITLE
issue related to  create_osp_model(pyfile==true)

### ISSUE THREAD

**Issue by Mehrshad-Ghorbanzadeh** [MonashSmartStructures/ospgrillage#100]
Dear developer, 
I recently worked on your amazing work (opsgrillage), suddenly, I noticed that when I want to put the option pyfile on true in create_osp_model function, I received the error as below: 
"Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\WorkFllow_Python\t1_gr.py", line 313, in <module>
    move_results = simple_grid.get_results(load_case="Moving Two Axle Truck")
  File "C:\Python38\lib\site-packages\ospgrillage\osp_grillage.py", line 2244, in get_results
    extract_da = basic_da.sel(Loadcase=name)
AttributeError: 'NoneType' object has no attribute 'sel'"

this is about basic_da that has no contribute to sel function. but it is work fluently when you put the option on false. can you help me to understand this mentioned issue. maybe it is my fault. 
I want to have the complete file to do some reliability analysis like your appreciated work. 

yours sincerely, 
Mehrshad Ghorbanzadeh

**Comment by justinngan92** [comment]
Hi @Mehrshad-Ghorbanzadeh,

Thank you for reaching out. 

On your first question, setting pyfile=True only **generates a python script that create the grillage model when executed**. If you have other commands following the line of create_osp_model(pyfile=True) then it wont work because the grillage model is technically "not created in the opensees space yet".

Hope this helps. Let us know if you have any questions.

**Comment by Mehrshad-Ghorbanzadeh** [comment]
Thank you for the clarification. I want to create a GUI using your awesome work in order to implement in variety issues.
I let you know and I need your help.
Thank you in advance.
